services:
  - type: web
    name: contactpro
    runtime: dotnet
    buildCommand: dotnet publish -c Release -o output
    startCommand: dotnet ContactPro.dll
    env: 
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://*:5000
      CONNECTIONSTRINGS__DEFAULTCONNECTION: postgres://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}
      # Email configuration (set these in Render dashboard)
      MAILSETTINGS__MAIL: ${MAIL_USER}
      MAILSETTINGS__DISPLAYNAME: ${MAIL_DISPLAYNAME}
      MAILSETTINGS__PASSWORD: ${MAIL_PASSWORD}
      MAILSETTINGS__HOST: ${MAIL_HOST}
      MAILSETTINGS__PORT: ${MAIL_PORT}

  - type: postgresql
    name: contactpro-db
    plan: free
    databaseName: contactpro
    user: contactpro